# Generated by Django 5.1.4 on 2025-01-13 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workspace',
            old_name='users',
            new_name='members',
        ),
        migrations.AddField(
            model_name='workspace',
            name='join_code',
            field=models.CharField(blank=True, editable=False, max_length=8),
        ),
    ]
