# Generated by Django 5.1.4 on 2025-02-03 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0003_rename_done_subtask_is_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='prio',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=10),
        ),
    ]
