# Generated by Django 5.1.4 on 2025-02-03 12:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0004_task_prio'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='selected_contacts',
            field=models.ManyToManyField(blank=True, related_name='selected_tasks', to=settings.AUTH_USER_MODEL),
        ),
    ]
