# Generated by Django 5.1.4 on 2025-02-09 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0005_task_selected_contacts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('done', 'Done'), ('awaitingFeedback', 'Awaiting Feedback'), ('todo', 'To Do'), ('inProgress', 'In Progress')], default='todo', max_length=20),
        ),
    ]
