# Generated by Django 5.1.4 on 2025-01-13 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth_app', '0003_customuser_connections'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='connections',
        ),
    ]
