# Generated by Django 5.1.4 on 2025-01-25 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth_app', '0004_remove_customuser_connections'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='avatar',
            field=models.CharField(blank=True, max_length=2),
        ),
        migrations.AddField(
            model_name='customuser',
            name='color',
            field=models.CharField(blank=True, max_length=7),
        ),
    ]
