# Generated by Django 5.1.4 on 2025-01-25 04:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth_app', '0005_customuser_avatar_customuser_color'),
        ('workspaces', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='avatar',
            field=models.CharField(max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='color',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='workspaces.color'),
        ),
    ]
