# Generated by Django 5.1.4 on 2025-01-25 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth_app', '0006_alter_customuser_avatar_alter_customuser_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='color',
            field=models.CharField(max_length=7, null=True),
        ),
    ]
