# Generated by Django 5.1.4 on 2025-01-25 18:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colors', '0001_initial'),
        ('user_auth_app', '0008_remove_customuser_avatar_remove_customuser_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='color',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='colors.color'),
            preserve_default=False,
        ),
    ]
