# Generated by Django 5.1.4 on 2025-01-25 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth_app', '0009_customuser_color'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='color',
        ),
    ]
