# Generated by Django 5.1.4 on 2025-01-27 13:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colors', '0002_rename_code_color_hex_value'),
        ('user_auth_app', '0012_customuser_avatar'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('avatar', models.CharField(blank=True, max_length=2, null=True)),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='colors.color')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
