# Generated by Django 5.1.4 on 2025-01-25 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('colors', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='color',
            old_name='code',
            new_name='hex_value',
        ),
    ]
